// client.react/src/Board.tsx
import classNames from 'classnames';
import React, { useMemo } from 'react';
import './Board.css';
import Field from './Field';

export interface BoardProps {
	fields: number[][];
	highlight?: [number, number][];
	active?: boolean;
	onItemClick?: (x: number, y: number) => void;
}

const Board: React.FC<BoardProps> = ({ fields, highlight, active, onItemClick }) => {

	const renderedFields = useMemo(() => {
		function shouldHighlight(x: number, y: number) {
			return highlight != null && highlight.some(([x0, y0]) => x0 === x && y0 === y);
		}

		return fields.map((row, y) => {
			return (
				<div key={y} style={{ display: 'flex' }}>
					{row.map((item, x) => {
						return (
							<Field key={`${x},${y}`} onClick={() => onItemClick?.call(null, x, y)} highlight={shouldHighlight(x, y)} player={item} />
						);
					})}
				</div>
			);
		});
	}, [fields, highlight, onItemClick]);

	return (
		<div className={classNames({ board: true, active })}>
			{renderedFields}
		</div>
	);
};

export default Board;

// client.angular/src/app/ttt/board/board.component.ts
import { Component, EventEmitter, HostBinding, Input, Output, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-board',
  templateUrl: './board.component.html',
  styleUrl: './board.component.css',
  encapsulation: ViewEncapsulation.ShadowDom,
})
export class BoardComponent {

  @HostBinding('hidden')
  get isHidden() { return !this.fields; }

  @Input({ required: true })
  fields?: number[][];

  @Input()
  highlight?: [number, number][];

  @Output()
  itemClicked = new EventEmitter<{ x: number, y: number }>;

  onItemClicked(x: number, y: number) {
    this.itemClicked.emit({ x: x, y: y });
  }

  shouldHighlight(x: number, y: number) {
    return this.highlight != null && this.highlight.some(([x0, y0]) => x0 === x && y0 === y);
  }
}

@for (row of fields; track y; let y = $index) {
<div style="display: flex;">
  @for (item of row; track x; let x = $index) {
  <app-field (click)="onItemClicked(x, y)" [player]="item" [highlight]="shouldHighlight(x, y)" />
  }
</div>
}
