// client.angular/src/app/ttt/game/game.component.ts
import { Component, Input, OnInit, ViewEncapsulation } from '@angular/core';
import { WebSocketSubject, webSocket } from 'rxjs/webSocket';
import { MessageType, BadRequestMessage, NewPlayerMessage, TurnMessage, UpdateMessage, Envelope } from '/TicTacToe/api.models';
import { SessionService } from '/app/session.service';

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['/src/styles.css', './game.component.css'],
  encapsulation: ViewEncapsulation.ShadowDom,
})
export class GameComponent implements OnInit {

  @Input({ alias: 'id', required: true })
  gameId!: string;

  private socket!: WebSocketSubject<Envelope>;

  playerCount: number = 0;
  myPlayerNumber: number = 0;
  currentPlayer: number = 0;
  board!: number[][];
  turnCount: number = 0;
  isComplete?: boolean;
  winner?: number;
  winningFields?: [number, number][];
  points: number[] = [0, 0, 0];

  constructor(private session: SessionService) { }

  ngOnInit(): void {
    this.board = [
      [0, 0, 0],
      [0, 0, 0],
      [0, 0, 0]
    ];

    this.socket =
      webSocket({
        url: `wss://${window.location.host}/api/tictactoe/${this.gameId}?cid=${this.session.clientId}`,
      });

    this.socket.subscribe({
      next: this.onMessage.bind(this),
      error: err => console.log('socket error', err),
      complete: () => console.log('socket closed'),
    });
  }

  private async onMessage(msg: Envelope) {
    console.log('<--', MessageType[msg.type], msg);

    switch (msg.type) {
      case MessageType.BadRequest:
        this.onBadRequest(<BadRequestMessage>msg.data);
        break;
      case MessageType.NewPlayer:
        this.onNewPlayer(<NewPlayerMessage>msg.data);
        break;
      case MessageType.Update:
        this.onUpdate(<UpdateMessage>msg.data);
        break;
      default:
        console.log(`Message ${MessageType[msg.type]} is unhandled`);
    }
  }

  private onBadRequest(msg: BadRequestMessage) {
    console.log(`<-- BadRequest: ${msg.message}`);
  }

  private onNewPlayer(msg: NewPlayerMessage) {
    console.log(`<-- NewPlayer: ${msg.currentPlayerNumber}`);
    this.myPlayerNumber = msg.currentPlayerNumber;
    this.playerCount = msg.playerCount;
  }

  private onUpdate(msg: UpdateMessage) {
    console.log(`<-- Update: ${msg.board}`);
    this.board = msg.board;
    this.currentPlayer = msg.currentPlayer;
    this.isComplete = msg.isComplete;
    this.turnCount = msg.turnCount;
    this.winner = msg.winner;
    this.winningFields = msg.winningFields;
    this.points = msg.points;
  }

  itemClicked(x: number, y: number) {
    let active = this.currentPlayer === this.myPlayerNumber;
    console.log(`Game: Clicked [${x}, ${y}]; active=${active}`);
    if (active)
      this.send(MessageType.Turn, <TurnMessage>{ x, y });
  }

  restartGame() {
    this.send(MessageType.Restart, null!);
  }

  private send(type: MessageType, data: any) {
    this.socket.next(<Envelope>{ type, data });
  }

  copyUrl() {
    navigator.clipboard.writeText(window.location.href);
  }
}

<p style="cursor: pointer;" title="Click to copy URL" (click)="copyUrl()">Lobby number: {{gameId}}</p>
<div class="game">
  <app-board [fields]="board" [highlight]="winningFields" (itemClicked)="itemClicked($event.x, $event.y)" [class.active]="myPlayerNumber === currentPlayer" />
  <div class="info">
    <div>
      <div>You are: </div><app-field [player]="myPlayerNumber" />
      @if(!isComplete) {
      <div>Now plays: </div><app-field [player]="currentPlayer" />
      }
      @else {
      <div>Winner: </div><app-field [player]="winner!" />
      }
    </div>
  </div>
</div>
<div class="status">
  <span>Players</span>
  <span>{{playerCount}}</span>
  <span>Turns</span>
  <span>{{turnCount}}</span>
  <span>Wins</span>
  <span>{{points[myPlayerNumber]}}</span>
  <span>Losses</span>
  <span>{{points[(myPlayerNumber % 2) + 1]}}</span>
  <span>Draws</span>
  <span>{{points[0]}}</span>
</div>
<button (click)="restartGame()">Restart!</button>

// client.react/src/Game.tsx
import { BadRequestMessage, Envelope, MessageType, NewPlayerMessage, TurnMessage, UpdateMessage } from '@lib/TicTacToe/api.models';
import React, { forwardRef, useCallback, useContext, useImperativeHandle, useLayoutEffect, useReducer, useRef } from 'react';
import { useParams } from 'react-router-dom';
import { AppContext } from './App';
import Board from './Board';
import Field from './Field';
import './Game.css';

function copyUrl() {
	navigator.clipboard.writeText(window.location.href);
}

interface GameState {
	playerCount: number;
	myPlayerNumber: number;
	currentPlayer: number;
	board: number[][];
	turnCount: number;
	isComplete: boolean;
	winner?: number;
	winningFields?: [number, number][];
	points: number[];
}

function initState(): GameState {
	return {
		board: [
			[0, 0, 0],
			[0, 0, 0],
			[0, 0, 0],
		],
		currentPlayer: 0,
		isComplete: true,
		myPlayerNumber: 0,
		playerCount: 0,
		points: [0, 0, 0],
		turnCount: 0,
		winner: undefined,
		winningFields: undefined,
	};
}

function reducer(state: GameState, msg: Envelope) {
	console.log('<--', MessageType[msg.type], msg);

	switch (msg.type) {
		case MessageType.BadRequest:
			return onBadRequest(state, msg.data as BadRequestMessage);
		case MessageType.NewPlayer:
			return onNewPlayer(state, msg.data as NewPlayerMessage);
		case MessageType.Update:
			return onGameStateUpdate(state, msg.data as UpdateMessage);
		default:
			console.log(`Message ${MessageType[msg.type]} is unhandled`);
			return state;
	}
}

function onBadRequest(state: GameState, msg: BadRequestMessage): GameState {
	console.log(`<-- BadRequest: ${msg.message}`);
	return state;
}

function onNewPlayer(state: GameState, msg: NewPlayerMessage): GameState {
	console.log(`<-- NewPlayer: ${msg.currentPlayerNumber}`);

	return {
		...state,
		myPlayerNumber: msg.currentPlayerNumber,
		playerCount: msg.playerCount,
	};
}

function onGameStateUpdate(state: GameState, msg: UpdateMessage): GameState {
	console.log(`<-- Update: ${msg.board}`);

	return {
		...state,
		board: msg.board,
		currentPlayer: msg.currentPlayer,
		isComplete: msg.isComplete,
		points: msg.points,
		turnCount: msg.turnCount,
		winner: msg.winner,
		winningFields: msg.winningFields,
	};
}

interface GameConnectionProps {
	gameId: string;
	clientId: string;
	onMessage: (msg: Envelope) => void,
}

interface GameConnectionMethods {
	send: (type: MessageType, data: unknown) => void,
}

let counter = 0;

const GameConnection = forwardRef((props: GameConnectionProps, ref: React.Ref<GameConnectionMethods>) => {

	const state = useRef<GameConnectionProps & { socket?: WebSocket | null }>({
		...props,
	});

	useImperativeHandle(ref, () => {
		return {
			send: function (type: MessageType, data: unknown) {
				const msg: Envelope = { type, data };
				state.current.socket?.send(JSON.stringify(msg));
			}
		};
	}, []);

	useLayoutEffect(() => {
		const { gameId, clientId, onMessage } = state.current;
		const socket = new WebSocket(`wss://${window.location.host}/api/tictactoe/${gameId}?cid=${clientId}`);
		const $id = ++counter;

		console.log(`Socket(${$id}) opening`);

		socket.addEventListener('open', function () {
			console.log(`Socket(${$id}) opened`);
		});

		socket.addEventListener('message', function (msg: MessageEvent<string>) {
			console.log(`Socket(${$id}) inc msg`);
			onMessage(JSON.parse(msg.data));
		});

		socket.addEventListener('close', function (ev: CloseEvent) {
			console.log(`Socket(${$id}) closed: code=${ev.code}, reason=${ev.reason}, wasClean=${ev.wasClean}`)
		});

		socket.addEventListener('error', function (ev: Event) {
			console.error(`Socket(${$id}) error:`, ev);
		});

		state.current.socket = socket;

		return () => {
			console.log(`Clean-up game(${$id}) connection; closing 1`);
			socket.close();

			if (socket.readyState === socket.CONNECTING) {
				socket.addEventListener('open', function () {
					console.log(`Clean-up game(${$id}) connection; closing 2`);
					this.close();
				});
			}
		};
	}, []);

	return (
		<></>
	);
});

const Game: React.FC = () => {
	const { id: gameId } = useParams();
	const appContext = useContext(AppContext);
	const [state, dispatch] = useReducer(reducer, null, initState);
	const connection = useRef<GameConnectionMethods>(null);

	const clientId = appContext.clientId;

	function send(type: MessageType, data: unknown) {
		connection.current!.send(type, data);
	}

	const playTurn = useCallback((x: number, y: number) => {
		const active = state.currentPlayer === state.myPlayerNumber;
		console.log(`Game: Clicked [${x}, ${y}]; active=${active}`);
		if (active)
			send(MessageType.Turn, { x, y } as TurnMessage);
	}, [state.currentPlayer, state.myPlayerNumber]);

	const restartGame = useCallback(() => {
		send(MessageType.Restart, null!);
	}, []);

	function foo(a: Envelope) {
		console.log('foo', a);
		dispatch(a);
	}

	return (
		<>
			{gameId && <GameConnection key={`${gameId},${clientId}`} gameId={gameId} clientId={clientId} onMessage={foo} ref={connection} />}
			<div>
				<p style={{ 'cursor': 'pointer' }} title="Click to copy URL" onClick={copyUrl}>Lobby number: {gameId}</p >
				<div className="game">
					<Board fields={state.board} highlight={state.winningFields} onItemClick={playTurn} active={state.myPlayerNumber === state.currentPlayer} />
					<div className="info">
						<div>
							<div>You are: </div><Field player={state.myPlayerNumber} />
							{!state.isComplete
								? (<><div>Now plays: </div><Field player={state.currentPlayer} /></>)
								: (<><div>Winner: </div><Field player={state.winner!} /></>)
							}
						</div>
					</div>
				</div>
				<div className="status">
					<span>Players</span>
					<span>{state.playerCount}</span>
					<span>Turns</span>
					<span>{state.turnCount}</span>
					<span>Wins</span>
					<span>{state.points[state.myPlayerNumber]}</span>
					<span>Losses</span>
					<span>{state.points[(state.myPlayerNumber % 2) + 1]}</span>
					<span>Draws</span>
					<span>{state.points[0]}</span>
				</div>
				<button onClick={restartGame}>Restart!</button >
			</div>
		</>
	);
};

export default Game;
