// client.angular/src/app/home/home.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, ViewEncapsulation } from '@angular/core';
import { Router } from '@angular/router';

interface CreateGameResult {
  gameId: string;
}

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['/src/styles.css', './home.component.css'],
  encapsulation: ViewEncapsulation.ShadowDom,
})
export class HomeComponent {

  constructor(private http: HttpClient, private router: Router) { }

  createLobby() {
    this.http.post<CreateGameResult>('/api/tictactoe', null).subscribe(data => {
      this.joinLobby(data.gameId);
    });
  }

  joinLobby(id: string) {
    this.router.navigate(['lobby', id]);
  }
}

<button (click)="createLobby()">Create lobby</button>
<label>
  or join existing
  <input #lobbyInput (keyup.enter)="joinLobby(lobbyInput.value)" />
</label>
<button (click)="joinLobby(lobbyInput.value)">Join</button>

// client.react/src/Home.tsx
import React, { useCallback, useRef } from 'react';
import { useNavigate } from 'react-router-dom';

interface CreateGameResult {
	gameId: string;
}

export default function Home() {
	const refInput = useRef<HTMLInputElement>(null);
	const navigate = useNavigate();

	const joinLobby = useCallback((id: string) => {
		navigate(`/lobby/${id}`)
	}, [navigate]);

	const joinLobbyClicked = useCallback(() => {
		joinLobby(refInput.current!.value);
	}, [joinLobby, refInput]);

	const keyHandler = useCallback((ev: React.KeyboardEvent<HTMLInputElement>) => {
		if (ev.key === 'Enter')
			joinLobbyClicked();
	}, [joinLobbyClicked]);

	const createLobby = useCallback(async () => {
		const response = await fetch('/api/tictactoe', {
			method: 'POST',
		});

		if (response.ok) {
			const result: CreateGameResult = await response.json();
			joinLobby(result.gameId);
		}
	}, [joinLobby]);

	return (
		<>
			<button onClick={createLobby}>Create lobby</button >
			<label>
				<span> or join existing </span>
				<input ref={refInput} onKeyUp={keyHandler} />
			</label>
			<button onClick={joinLobbyClicked}>Join</button >
		</>
	);
}
